### ISSUE TITLE
Way to make the with out

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Html#16]
Hi Paul, 

I forget there is a way to call `h()`, `j()` etc without making use of 

``` php
<?php 
use Aura\Html\Escaper as e; 
e::h('Hello World');
?>
```

like adding a `functions.php` file and having something like 

``` php
<?php
use Aura\Html\Escaper; 
function h($raw) 
{
    return Escaper::h($raw);
}
```

And this can be autoloaded by composer. 

And I would like to alter the getStatic() to make sure the Escaper object is there.

``` php
    public static function getStatic()
    {
        if (! static::$escaper) {
            $html = new HtmlEscaper($this->flags, $this->encoding);
            $attr = new AttrEscaper($html, $this->encoding);
            $css = new CssEscaper($this->encoding);
            $js = new JsEscaper($this->encoding);
            static::$escaper = new self($html, $attr, $css, $js);
        }
        return static::$escaper;
    }
```

This make calling as `h("Hello World")` I guess :+1:  .

Not sure whether you like or not.

**Comment by pmjones** [comment]
Hm. That looks like the functions are global, which is something I'd rather avoid. Bad enough to be using static methods.
