### ISSUE TITLE
Calling helpers inside helpers

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Html#20]
I don't see a way to call the helpers inside the helpers. 

Else we need to duplicate the code of the other html helpers.

**Comment by harikt** [comment]
``` php
 // May be in the Aura/Html/HelperLocator
public function __call($name, $args)
{
    $helper = $this->get($name);
    $helper->setLocator($this);
    return call_user_func_array(
        $helper,
        $args
    );
}
```

and in the `Aura\Html\Helper\AbstractHelper` , we add the `__call` method which calls the helper locator?

Do you think that is ok to go?

**Comment by pmjones** [comment]
In theory, what you would want to do is inject the helper you need into the helper that needs it, and not (in general) the locator for all helpers. There are exceptions, such as with the input helper, but even then it gets a locator specific to its own needs, not the all-purpose locator.
