### ISSUE TITLE
Continuation of the Numeric Keys for Options issue

### ISSUE THREAD

**Issue by bsahlhof** [auraphp/Aura.Html#21]
I found where you fixed the Select issue for this, but the same issue can be found within Aura\Html\Helper\Input\AbstractChecked, which causes issues with the radio inputs (since they are set using the options array as well).  Could you implement the same fix you did with the Select, or create a different fix?

**Comment by pmjones** [comment]
Hi @bsahlhof sorry to take so long to get back to you. Which Select issue was this, so I can look it up and apply a similar fix?

**Comment by pmjones** [comment]
Do you mean https://github.com/auraphp/Aura.Html/blob/develop-2/src/Helper/Input/Radio.php#L51-L59, perhaps? If that's the case, it's not necessarily wise to assume that an integer `$value` should use `$label` as the value instead, because it might be that the value is **supposed** to be an integer.

If that's not the case, let me know.

**Comment by bsahlhof** [comment]
I'll review when I'm near my development pc, but the issue was that when
the key of the options were integers (Which converted to the value, not the
label), when the check was made, it would always come back false...
specifically because of these lines:
https://github.com/auraphp/Aura.Html/blob/develop-2/src/Helper/Input/AbstractChecked.php#L68-L81

I have not checked this functionality for quite some time, but assuming the
issue wasn't previously fixed, then the strict === causes this statement to
always be false if integers (or, I believe string numbers) were used within
the array passed in. ( 1 !== '1' )

**Comment by pmjones** [comment]
Ah so! In Select, we solved it with a `$strict` property that could be turned off and on. I'll try that here too.

**Comment by harikt** [comment]
@pmjones no tests ;) .

**Comment by pmjones** [comment]
Good grief @harikt give it five minutes. ;-)

**Comment by harikt** [comment]
:) . noticed .
