### ISSUE TITLE
Better frontend integration

### ISSUE THREAD

**Issue by thejw23** [auraphp/Aura.Html#22]
Is there any way to use decorators in forms? It would be nice to switch between default raw HTML, Foundation, Bootstrap and other CSS frameworks.

**Comment by harikt** [comment]
can you give me an example what you are looking for ?

**Comment by thejw23** [comment]
Most pages use some kind of CSS framework. Like in https://github.com/Anahkiasen/former/wiki/Features - there is Former::framework('TwitterBootstrap'); and the html result TB friendly.

I guess it would be nice to have that feature, some kind of plugin system, a kind of decorator to adding additional HTML to various Aura.HTML form elements. In example, a plugin that can add to every generated input proper divs with class "control-group", and so on. It would be easier to create/validate/pupulate forms with separate class using Aura.HTML/Input and push the result to view with one line in there echo $form. If I change CSS framework I just create and activate different plugin/decorator - no need to change views and mess with divs, Aura.HTML will handle everything for me.

**Comment by harikt** [comment]
:) , I get you.

I have played with decorators of zf v1 , and it is a monster. 
I don't like it, and I don't think Paul do love the  idea.

**Comment by thejw23** [comment]
Then I guess I need to make my own proxy class witch will handle desired features with Aura.HTML/Input under the hood :) Hope to see such feature someday, it's very handy to controll all form within one application class and just pass output to the view.

**Comment by pmjones** [comment]
At this point, I think wrapping with your own proxy (or other) is the way to go.
