### ISSUE TITLE
Assign authority to @jakejohns

### ISSUE THREAD

**Issue by pmjones** [auraphp/Aura.Html#51]
@jakejohns Since you are putting so much effort into this package, and since I am so  slow to respond, how would you feel about becoming the package owner? Full authority and responsibility over it, etc. (And if you can't, no big deal.) Thanks, hope you are doing well!

**Comment by jakejohns** [comment]
How much authority are we talking here? While I'm flattered, I'd be worried about the integrity of the project without your direct oversight. I tend to defer to your expertise in numerous matters.

**Comment by pmjones** [comment]
> How much authority are we talking here?

You'd basically get "admin" status on the repo, which gives you push/pull/etc rights.

>  without your direct oversight

I'd be happy to provide as much oversight as you're willing to take. 

Feel free to decline; if you are content waiting on me for responses, I'm cool with it too. :-)

**Comment by jakejohns** [comment]
Perhaps I should step up and accept some responsibility. I think a couple of those PR's are probably acceptable enough.

**Comment by pmjones** [comment]
@jakejohns Is that a yes? :-)

**Comment by harikt** [comment]
@pmjones may be add @jakejohns as organization member then?

**Comment by harikt** [comment]
@pmjones  How is the release process going to be for Aura.Html ?

As you are the primary person who normally do releases, wondering it may be good to give authority for Aura.Html to get releases by @jakejohns . So he can do releases when ever new stuffs are added.

Also there is a few repos that people where looking for releases or either things to be merged. Could you please look into Aura.Di which has added a few commits after March iirc which has not been released. Also there is a PR waiting for your review.

Thank you.

**Comment by pmjones** [comment]
> it may be good to give authority for Aura.Html to get releases by @jakejohns

Yes, I agree. I will look at the "release a package" code today and make sure it can be used by others.

**Comment by harikt** [comment]
Thanks for your time Paul.

**Comment by pmjones** [comment]
@jakejohns @harikt I have made some updates to the [auraphp/bin](https://github.com/auraphp/bin) repository; the new instructions there _should_ be sufficient for you to make releases. Clone the repo locally, `composer install` inside it, and follow the README.

Let me know when you run into trouble. (I expect you will because this is the first time anyone besides me has done a release, and I figure there are thing I have forgotten to document.)

Thanks guys!

**Comment by harikt** [comment]
Sure, thanks for your efforts.

**Comment by harikt** [comment]
One issue I noticed was https://github.com/auraphp/bin/issues/6 . 

Apart from that all is fine. Closing the issue for we could communicate in aura/bin the remaining issues for this is not regarding Aura.Html anymore.

Thanks all.
