### ISSUE TITLE
Released 2.5.0!

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Html#57]
@harikt I went ahead and released 2.5.0 as we talked about in #53.

Perhaps I was a bit hasty,  since I just opened #55, but I got a little excited when you figured out the stuff with travis. :)

**Comment by harikt** [comment]
@jakejohns Congrats on doing your first release.

Go ahead and tweet about the new version with cc auraphp .
Send an email to google groups about the release and notify people.

Congrats once again.
