### ISSUE TITLE
PHP 8.1: ctype_digit(): Argument of type int will be interpreted as string in the future

### ISSUE THREAD

**Issue by arokettu** [auraphp/Aura.Html#59]
The check in ``if ($raw === '' || ctype_digit($raw)) {`` throws a deprecation warning in PHP 8.1:

```
ctype_digit(): Argument of type int will be interpreted as string in the future
```

There are 2 places: AbstractEscaper:119 and HtmlEscaper:68

I think the best solution is to cast $raw to string in the beginning

**Comment by harikt** [comment]
Thanks for the report. Once we get some time will look into it.
