### ISSUE TITLE
Issue then using numeric key for options

### ISSUE THREAD

**Issue by dmolineus** [auraphp/Aura.Html#6]
I have to fill my select widget with options, which contains numeric keys. Unfortunately the select helper does not detect the selected value because of the strict value checking in https://github.com/auraphp/Aura.Html/blob/develop-2/src/Helper/Input/Select.php#L257

``` php
// example with integer keys
$options = array('one', 'two');
$field->setOptions($options);

// example with string keys, but converted to integers by php
$options = array('0' => 'one', '1' => 'two');
$field->setOptions($options);
```

Both examples will have integer array keys.

There seems to be some issues with the automatically type convertion of PHP.
1. PHP gets numbers as string in  `$_POST` (I simply filled my form using the post array)
2. PHP converts numeric keys set as string to integers in arrays.
3. The select helper will fail because the post value is a string, the defined value is an integer.

Maybe something is wrong with my PHP setup but at the moment I can not use the select helpers because of the strict value checking.

**Comment by harikt** [comment]
patch it for now the strict checking.

I can also look when I get some time.

Busy at work :( .

**Comment by jelofson** [comment]
+1 
I would agree that strict checking causes confusion due to php's type conversion.
